// Mock data fallback when API fails
export const MOCK_MOVIES = [
  {
    id: 1,
    title: "Dune: Part Two",
    original_title: "Dune: Part Two",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    poster_path: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlDjQ0DHAeN5nR.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    vote_average: 8.3,
    release_date: "2024-03-01",
    genre_ids: [878, 12, 28],
    media_type: "movie",
  },
  {
    id: 2,
    title: "Oppenheimer",
    original_title: "Oppenheimer",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    poster_path: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    vote_average: 8.1,
    release_date: "2023-07-19",
    genre_ids: [18, 36],
    media_type: "movie",
  },
  {
    id: 3,
    title: "Poor Things",
    original_title: "Poor Things",
    overview: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    poster_path: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXEOEYqzqHcAi6T.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
    vote_average: 7.8,
    release_date: "2023-12-08",
    genre_ids: [35, 18, 878],
    media_type: "movie",
  },
  {
    id: 4,
    title: "Godzilla x Kong: The New Empire",
    original_title: "Godzilla x Kong: The New Empire",
    overview: "Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins and connection to Skull Island's mysteries.",
    poster_path: "https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/fY3lD0jM5AoHJMunjGWqJ0hRteI.jpg",
    vote_average: 7.0,
    release_date: "2024-03-27",
    genre_ids: [28, 878, 12],
    media_type: "movie",
  },
  {
    id: 5,
    title: "Kung Fu Panda 4",
    original_title: "Kung Fu Panda 4",
    overview: "Po is chosen to become the Spiritual Leader of the Valley of Peace but needs to find and train a new Dragon Warrior.",
    poster_path: "https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/vdpE5pjJVql5aD6ymsNOrlmxvhb.jpg",
    vote_average: 7.2,
    release_date: "2024-03-08",
    genre_ids: [16, 35, 28, 10751],
    media_type: "movie",
  },
  {
    id: 6,
    title: "Civil War",
    original_title: "Civil War",
    overview: "A journey across a dystopian future America, following a team of military-embedded journalists as they race against time to reach DC before rebel factions descend on the White House.",
    poster_path: "https://image.tmdb.org/t/p/w500/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/ugZgMX8KBKhWfCCLB2yWBaRr6GS.jpg",
    vote_average: 7.5,
    release_date: "2024-04-12",
    genre_ids: [28, 18, 53],
    media_type: "movie",
  },
  {
    id: 7,
    title: "Furiosa: A Mad Max Saga",
    original_title: "Furiosa: A Mad Max Saga",
    overview: "The origin story of renegade warrior Furiosa before she teamed up with Mad Max in the post-apocalyptic world.",
    poster_path: "https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    vote_average: 7.7,
    release_date: "2024-05-22",
    genre_ids: [28, 12, 878],
    media_type: "movie",
  },
  {
    id: 8,
    title: "Inside Out 2",
    original_title: "Inside Out 2",
    overview: "Riley enters adolescence and new Emotions join Joy, Sadness, Anger, Fear, and Disgust in Headquarters.",
    poster_path: "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/xg27NrXi7VXCGUr7MlcbgrGnbN.jpg",
    vote_average: 7.8,
    release_date: "2024-06-14",
    genre_ids: [16, 10751, 35, 18],
    media_type: "movie",
  },
  {
    id: 9,
    title: "Deadpool & Wolverine",
    original_title: "Deadpool & Wolverine",
    overview: "Deadpool is recruited by the TVA and pairs up with a variant of Wolverine to save Deadpool's universe.",
    poster_path: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    vote_average: 7.9,
    release_date: "2024-07-26",
    genre_ids: [28, 12, 35],
    media_type: "movie",
  },
  {
    id: 10,
    title: "Alien: Romulus",
    original_title: "Alien: Romulus",
    overview: "A group of young people on a distant world, while trying to salvage the outer reaches of space, find themselves in the grasp of the most terrifying life form in the universe.",
    poster_path: "https://image.tmdb.org/t/p/w500/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    vote_average: 7.3,
    release_date: "2024-08-16",
    genre_ids: [27, 878, 53],
    media_type: "movie",
  },
];

export const MOCK_TV_SHOWS = [
  {
    id: 101,
    title: "The Last of Us",
    name: "The Last of Us",
    overview: "Joel, a smuggler, is tasked with escorting Ellie, a teenage girl, across a post-apocalyptic United States.",
    poster_path: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95eDDHeOC2.jpg",
    vote_average: 8.7,
    first_air_date: "2023-01-15",
    genre_ids: [18, 10759, 27],
    media_type: "tv",
  },
  {
    id: 102,
    title: "House of the Dragon",
    name: "House of the Dragon",
    overview: "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.",
    poster_path: "https://image.tmdb.org/t/p/w500/t9XkeE7HzOsdQcDDDapDYh8Rrmt.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    vote_average: 8.4,
    first_air_date: "2022-08-21",
    genre_ids: [10765, 18, 10759],
    media_type: "tv",
  },
  {
    id: 103,
    title: "Shogun",
    name: "Shogun",
    overview: "In feudal Japan, Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him.",
    poster_path: "https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/9UjfhutJpKlbYV5JEBXsv6LPCMR.jpg",
    vote_average: 8.8,
    first_air_date: "2024-02-27",
    genre_ids: [18, 10759],
    media_type: "tv",
  },
  {
    id: 104,
    title: "The Bear",
    name: "The Bear",
    overview: "A young chef from the fine dining world comes to run a family sandwich shop in Chicago.",
    poster_path: "https://image.tmdb.org/t/p/w500/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/4oCHPJ9QRNN3Q1AJQ3dOaqNtNzO.jpg",
    vote_average: 8.5,
    first_air_date: "2022-06-23",
    genre_ids: [18, 35],
    media_type: "tv",
  },
];

export const MOCK_ANIME = [
  {
    id: 201,
    title: "Attack on Titan Final Season",
    name: "Attack on Titan Final Season",
    overview: "The story of Eren Yeager who lives in a society where humans are living inside three massive walls to protect themselves from Titans.",
    poster_path: "https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg",
    vote_average: 9.0,
    first_air_date: "2020-12-07",
    genre_ids: [16, 10759, 18],
    media_type: "tv",
  },
  {
    id: 202,
    title: "Demon Slayer",
    name: "Demon Slayer: Kimetsu no Yaiba",
    overview: "Tanjiro sets out on the path of a Demon Slayer to save his sister and avenge his family.",
    poster_path: "https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/kFouSueyGDPtCxaIzUiHFxhHYb1.jpg",
    vote_average: 8.7,
    first_air_date: "2019-04-06",
    genre_ids: [16, 10759, 28],
    media_type: "tv",
  },
  {
    id: 203,
    title: "Solo Leveling",
    name: "Solo Leveling",
    overview: "In a world where hunters must battle deadly monsters to protect the human race, Sung Jinwoo, the weakest hunter of all, finds himself in a special double dungeon.",
    poster_path: "https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/rcxJFXCFfmAH0RJqxqR4TZMwqz9.jpg",
    vote_average: 8.4,
    first_air_date: "2024-01-06",
    genre_ids: [16, 10759, 18],
    media_type: "tv",
  },
  {
    id: 204,
    title: "Jujutsu Kaisen",
    name: "Jujutsu Kaisen",
    overview: "A boy swallows a cursed talisman – the finger of a demon – and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts.",
    poster_path: "https://image.tmdb.org/t/p/w500/7t35O94fGjmRfwrUVwK8klOc2Vv.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/mQHJ6XrRCOwHxvKFtKdRv1UEhPp.jpg",
    vote_average: 8.6,
    first_air_date: "2020-10-03",
    genre_ids: [16, 10759, 28],
    media_type: "tv",
  },
];

export const GENRES = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  27: "Horror",
  10749: "Romance",
  878: "Sci-Fi",
  53: "Thriller",
  10765: "Sci-Fi & Fantasy",
  10759: "Action & Adventure",
  36: "History",
};
